<?php

namespace Tests\Feature\RestApi;

use App\RestApi\Http\Aggregation;
use Tests\TestCase;

class AggregationTest extends TestCase
{
    public $aggregation;

    public function setUp(): void
    {
        $this->aggregation = new Aggregation();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @group aggregation
     *
     * @return void
     */
    public function testExample()
    {
        $result = $this->aggregation->buckets();

        $result = $this->aggregation->bucketsAndStats();

        $result = $this->aggregation->pipelineBuckets();


        dd($result);
    }
}
