<?php

namespace Tests\Feature\RestApi;

use App\RestApi\Http\Analyzer;
use Tests\TestCase;

class AnalyzerTest extends TestCase
{
    public $analyzer;

    public function setUp(): void
    {
        $this->analyzer = new Analyzer();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @group analyzer
     *
     * @return void
     */
    public function testExample()
    {
        $analyzer = 'standard';
        $test = '2 running Quick brown-foxes leap over lazy dogs in the summer evening.';
        $result = $this->analyzer->testByAnalyzer($analyzer, $test);

        $char_filter = [
            "type" => "mapping",
            "mappings" => [
                ":) => happy",
                ":( => sad"]
        ];
        $tokenizer = 'standard';
        $filter = ["stop","snowball"];
        $result = $this->analyzer->testByCustom($char_filter, $tokenizer, $filter, $test);

        $result = $this->analyzer->mappingDefinitionAnalyzer();

        dd($result);
    }
}
